feat: sort place's demands by date
copotrzebne-pl/copotrzebne-api pull request #153
Opened 2022-05-11 14:28 UTC by jakubgwozdz

as described in #143

2022-05-11 15:10 UTC, michaldomagalski requested changes

2022-05-11 20:31 UTC, jakubgwozdz commented on src/demands/services/demands.service.ts
> +        ? [['createdAt', 'ASC']]
oh... right!

2022-05-11 20:34 UTC, jakubgwozdz commented on src/demands/types/sort.type.enum.ts
> +export enum Sort {
I have no opinion on that so I'll follow suit, no problem :)

2022-05-12 04:59 UTC, michaldomagalski approved these changes
Great! 🎉

2022-05-14 15:53 UTC, merged